[profile.default]
src = 'contracts'
out = 'target'
test = 'test'
libs = ['submodules']
solc_version = "0.8.16"
verbosity = 1
via_ir = false
remappings = [
    '/=contracts',
    "OpenZeppelin/=submodules/abracadabra-money-foundry/lib/openzeppelin-contracts/contracts",
    "BoringSolidity/=submodules/abracadabra-money-foundry/lib/BoringSolidity/contracts",
    "ds-test/=submodules/abracadabra-money-foundry/lib/forge-std/lib/ds-test/src/",
    "forge-std/=submodules/abracadabra-money-foundry/lib/forge-std/src/",
    'utils/=submodules/abracadabra-money-foundry/utils',
    'libraries/=submodules/abracadabra-money-foundry/src/libraries',
    'interfaces/=submodules/abracadabra-money-foundry/src/interfaces',
    'cauldrons/=submodules/abracadabra-money-foundry/src/cauldrons',
    'swappers/=submodules/abracadabra-money-foundry/src/swappers',
    'oracles/=submodules/abracadabra-money-foundry/src/oracles',
    'strategies/=submodules/abracadabra-money-foundry/src/strategies',
    'tokens/=submodules/abracadabra-money-foundry/rc/tokens',
    'harvesters/=submodules/abracadabra-money-foundry/src/harvesters',
    'periphery/=submodules/abracadabra-money-foundry/src/periphery',
    '@uniswap/v3-core/=submodules/v3-core',
    '@uniswap/v3-periphery/=submodules/v3-periphery',
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
